# for_debug
FOR_DEBUG: True        # True or False

MANUAL_SEED: 123
TRAIN_GPU:
  - 0

DATA_TYPE: "above-under_baseline"   # baseline or refine (or campus3d or above-under)

ARCH: "pptnet"
GLOBAL_FEAT: True
FEATURE_TRANSFORM: True
MAX_POOL: False
GROUP: 8

AGGREGATION: 'spvlad'
LAST_NORMALIZATION: False
NUM_POINTS: 4096

FEATURE_OUTPUT_DIM: 256

FEATURE_SIZE:
  - 256
  - 256
  - 256
  - 256

MAX_SAMPLES:
  - 64
  - 256
  - 1024
  - 4096

CLUSTER_SIZE:
  - 1
  - 4
  - 16
  - 64

OUTPUT_DIM:
  - 256
  - 256
  - 256
  - 256

GATING: True

SAMPLING:
  - 1024
  - 256
  - 64
  - 16

KNN:
  - 20
  - 20
  - 20
  - 20

DATASET_FOLDER: '/datasets/work/mlai-fsp-st-div/source/above-under/processed_submaps/latest/rad45m/postproc_pnvlad_ds_4096_normalised/'
# DATASET_FOLDER: '/datasets/work/mlai-fsp-st-div/source/above-under/pointnetvlad_datasets/'

# TRAIN
BATCH_NUM_QUERIES: 2
TRAIN_POSITIVES_PER_QUERY: 2
TRAIN_NEGATIVES_PER_QUERY: 14

DECAY_STEP: 200000
DECAY_RATE: 0.7

# BASE_LEARNING_RATE: 0.00001
BASE_LEARNING_RATE: 0.0005
MOMENTUM: 0.9
OPTIMIZER: 'adam'
MAX_EPOCH: 30

LEARNING_RATE_DECAY: 'step'

# the margin is too small
MARGIN_1: 0.5
MARGIN_2: 0.2

BN_INIT_DECAY: 0.5
BN_DECAY_DECAY_RATE: 0.5
BN_DECAY_CLIP: 0.99

TRAIN_FILE_ROOT: '/datasets/work/mlai-fsp-st-div/source/above-under/processed_submaps/latest/rad45m/postproc_pnvlad_ds_4096_normalised/'
TEST_FILE_ROOT: '/datasets/work/mlai-fsp-st-div/source/above-under/processed_submaps/latest/rad45m/postproc_pnvlad_ds_4096_normalised/'

# LOSS
LOSS_FUNCTION: 'quadruplet'
LOSS_LAZY: True
TRIPLET_USE_BEST_POSITIVES: False
LOSS_IGNORE_ZERO_BATCH: False

# EVAL6
EVAL_BATCH_SIZE: 8
EVAL_POSITIVES_PER_QUERY: 4
EVAL_NEGATIVES_PER_QUERY: 10
SKIP_SAME_RUN: True

DEGREE: 0

#  ----------- switch data for evaluation ----------
# EVAL_DATASET: 'Beetaloo'
# EVAL_DATABASE_FILE: '/datasets/work/mlai-fsp-st-div/source/above-under/processed_submaps/latest/rad45m/postproc_pnvlad_ds_4096_normalised/above-under_Beetaloo_evaluation_database.pickle'
# EVAL_QUERY_FILE: '/datasets/work/mlai-fsp-st-div/source/above-under/processed_submaps/latest/rad45m/postproc_pnvlad_ds_4096_normalised/above-under_Beetaloo_evaluation_query.pickle'

EVAL_DATASET: 'Karawatha'
EVAL_DATABASE_FILE: '/datasets/work/mlai-fsp-st-div/source/above-under/processed_submaps/latest/rad45m/postproc_pnvlad_ds_4096_normalised/above-under_Karawatha_evaluation_database.pickle'
EVAL_QUERY_FILE: '/datasets/work/mlai-fsp-st-div/source/above-under/processed_submaps/latest/rad45m/postproc_pnvlad_ds_4096_normalised/above-under_Karawatha_evaluation_query.pickle'

# EVAL_DATASET: 'QCAT'
# EVAL_DATABASE_FILE: '/datasets/work/mlai-fsp-st-div/source/above-under/processed_submaps/latest/rad45m/postproc_pnvlad_ds_4096_normalised/above-under_QCAT_evaluation_database.pickle'
# EVAL_QUERY_FILE: '/datasets/work/mlai-fsp-st-div/source/above-under/processed_submaps/latest/rad45m/postproc_pnvlad_ds_4096_normalised/above-under_QCAT_evaluation_query.pickle'

# EVAL_DATASET: 'Robson'
# EVAL_DATABASE_FILE: '/datasets/work/mlai-fsp-st-div/source/above-under/processed_submaps/latest/rad45m/postproc_pnvlad_ds_4096_normalised/above-under_Robson_evaluation_database.pickle'
# EVAL_QUERY_FILE: '/datasets/work/mlai-fsp-st-div/source/above-under/processed_submaps/latest/rad45m/postproc_pnvlad_ds_4096_normalised/above-under_Robson_evaluation_query.pickle'

# EVAL_DATASET: 'Samford'
# EVAL_DATABASE_FILE: '/datasets/work/mlai-fsp-st-div/source/above-under/processed_submaps/latest/rad45m/postproc_pnvlad_ds_4096_normalised/above-under_Samford_evaluation_database.pickle'
# EVAL_QUERY_FILE: '/datasets/work/mlai-fsp-st-div/source/above-under/processed_submaps/latest/rad45m/postproc_pnvlad_ds_4096_normalised/above-under_Samford_evaluation_query.pickle'